name: tfm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.16
  - numpy=1.21.6
  - pytorch=1.12.1
  - torchvision=0.13.0
  - albumentations=1.3.0
  - pyradiomics=3.0.1
  - pandas=1.3.5
  - pillow=9.2.0
  - matplotlib=3.5.3
  - segmentation_models_pytorch=0.3.0
  - simpleitk=2.2.1
  - six=1.16.0
  - imutils=0.5.4
  - opencv=4.6.0
  - scikit-learn=1.0.2
  - pip=22.3
  - pip:
      gradio==3.27.0
